const express = require('express');
const router = express.Router();
const { createAdmin, updateAdmin, deleteAdmin, listAdmins, listAdminsBasic, getAdminBatchAccess, toggleEmailNotifications, toggleSmsNotifications, getOwnProfile } = require('../controllers/adminController');
const { verifyToken, requireRole } = require('../middleware/auth');
router.get('/basic', verifyToken, listAdminsBasic);
router.get('/me', verifyToken, getOwnProfile);
router.use(verifyToken, requireRole('super_admin'));
router.get('/:id/batches', getAdminBatchAccess);
router.patch('/:id/notifications', toggleEmailNotifications);
router.patch('/:id/sms-notifications', toggleSmsNotifications);
router.post('/', createAdmin);
router.put('/:id', updateAdmin);
router.delete('/:id', deleteAdmin);
router.get('/', listAdmins);
module.exports = router;