const express = require('express');
const router = express.Router();
const { login, changePassword, verifyResetToken, setPassword, logout } = require('../controllers/authController');
const { verifyToken } = require('../middleware/auth');
const { doubleCsrfProtection } = require('../middleware/csrf');
const { loginLimiter } = require('../middleware/rateLimit');
router.post('/login', loginLimiter, doubleCsrfProtection, login);
router.post('/logout', logout);
router.post('/change-password', verifyToken, changePassword);
router.get('/verify-reset-token/:token', verifyResetToken);
router.post('/set-password', setPassword);
module.exports = router;