const express = require('express');
const router = express.Router();
const { verifyFacultyToken } = require('../middleware/auth');
const { doubleCsrfProtection } = require('../middleware/csrf');
const { loginLimiter } = require('../middleware/rateLimit');
const {facultyLogin, changeFacultyPassword, verifyFacultyResetToken, setFacultyPassword, facultyLogout} = require('../controllers/facultyAuthController');
router.post('/login', loginLimiter, doubleCsrfProtection, facultyLogin);
router.post('/logout', facultyLogout);
router.get('/verify-reset-token/:token', verifyFacultyResetToken);
router.post('/set-password', setFacultyPassword);
router.post('/change-password', verifyFacultyToken, changeFacultyPassword);
module.exports = router;