const express = require('express');
const router = express.Router();
const {generateSession, getSessionStatus, submitAttendance, getSessionReport, downloadSessionReport, issueDeviceToken} = require('../controllers/qrController');
const { verifyAdminOrFaculty } = require('../middleware/auth');
const { qrSubmitLimiter } = require('../middleware/rateLimit');
router.get('/device-token', issueDeviceToken);
router.post('/batch/:batchId/generate', verifyAdminOrFaculty, generateSession);
router.get('/:sessionId/report', verifyAdminOrFaculty, getSessionReport);
router.get('/:sessionId/download', verifyAdminOrFaculty, downloadSessionReport);
router.post('/:token/submit', qrSubmitLimiter, submitAttendance);
module.exports = router;