const express = require('express');
const router = express.Router();
const {studentLogin, getMyAttendance, getMyAssignments, submitAssignment} = require('../controllers/studentAuthController');
const { verifyStudentToken } = require('../middleware/auth');
const { uploadSubmissionFile } = require('../middleware/upload');
router.post('/login', studentLogin);
router.get('/me', verifyStudentToken, getMyAttendance);
router.get('/assignments', verifyStudentToken, getMyAssignments);
router.post('/assignments/:assignmentId/submit', verifyStudentToken, uploadSubmissionFile, submitAssignment);
module.exports = router;